GestionMusique/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^musiques/', include('musiques.urls')),
]

musiques/urls.py
from django.conf.urls import url, include
from . import views
from .views import MorceauDetailView, MorceauDeleteView, MorceauUpdateView, ArtisteDetailView, ArtisteListView, ArtisteDeleteView, ArtisteUpdateView, MorceauListView, MorceauCreateView, home, ArtisteCreateView


app_name = 'musiques'
urlpatterns = [
    url(r'^home$', home, name='home'),
    url(r'^detailArtiste/(?P<pk>\d+)$',
        ArtisteDetailView.as_view(), name='artiste-detail'),
    url(r'^listArtiste$', ArtisteListView.as_view(), name='artiste-list'),
    url(r'^addArtiste$', ArtisteCreateView.as_view(), name="artiste-add"),
    url(r'^delArtiste/(?P<pk>\d+)$',
        ArtisteDeleteView.as_view(), name='artiste-del'),
    url(r'^updateArtiste/(?P<pk>\d+)$',
        ArtisteUpdateView.as_view(), name='artiste-update'),
    url(r'^detailMorceau/(?P<pk>\d+)$',
        MorceauDetailView.as_view(), name='morceau-detail'),
    url(r'^listMorceau$', MorceauListView.as_view(), name='morceau-list'),
    url(r'^addMorceau$', MorceauCreateView.as_view(), name='morceau-add'),
    url(r'^delMorceau/(?P<pk>\d+)$',
        MorceauDeleteView.as_view(), name='morceau-del'),
    url(r'^updateMorceau/(?P<pk>\d+)$',
        MorceauUpdateView.as_view(), name='morceau-update'),
]

musiques/models.py
from django.db import models

# Create your models here.


class Artiste(models.Model):
    nom = models.CharField(max_length=64)

    def __str__(self):
        return '{self.nom}'.format(self=self)


class Morceau(models.Model):
    titre = models.CharField(max_length=64)
    artiste = models.ForeignKey(
        Artiste, on_delete=models.CASCADE, null=True)
    date_sortie = models.DateField(null=True)

    def __str__(self):
        return '{self.titre} ({self.artiste})'.format(self=self)

musiques/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView
#from django.views.generic.list import ListView
#from django.views.generic.edit import CreateView
#from django.views.generic.delete import DeleteView
from django.forms import ModelForm
from .models import Morceau, Artiste
from django.views.generic.edit import DeleteView


# Create your views here.


def home(request):
    return render(request, 'musiques/home.html')


class ArtisteDetailView(DetailView):
    model = Artiste
    template_name = 'musiques/artiste.html'


class ArtisteListView(ListView):
    model = Artiste

    def get_context_data(self, **kwargs):
        context = super(ArtisteListView, self).get_context_data(**kwargs)
        context['template'] = "musiques/listArtiste.html"
        return context


class ArtisteCreateView(CreateView):
    model = Artiste
    fields = ['nom']

    def get_success_url(self):
        return reverse('musiques:artiste-list')


class ArtisteDeleteView(DeleteView):
    model = Artiste

    def get_success_url(self):
        return reverse('musiques:artiste-list')


class ArtisteUpdateView(UpdateView):
    model = Artiste
    fields = ['nom']

    def get_success_url(self):
        return reverse('musiques:artiste-list')


class MorceauDetailView(DetailView):
    model = Morceau
    template_name = 'musiques/morceau.html'


class MorceauListView(ListView):
    model = Morceau

    def get_context_data(self, **kwargs):
        context = super(MorceauListView, self).get_context_data(**kwargs)
        context['template'] = 'musiques/listemorceau.html'
        return context


class MorceauCreateView(CreateView):
    model = Morceau
    fields = ['artiste', 'titre']

    def get_success_url(self):
        return reverse('musiques:morceau-list')

    def get_success_url(self):
        return reverse('musiques:morceau-list')


class MorceauUpdateView(UpdateView):
    model = Morceau
    fields = ['artiste', 'titre']

    def get_success_url(self):
        return reverse('musiques:morceau-list')

    def get_success_url(self):
        return reverse('musiques:morceau-list')


class MorceauDeleteView(DeleteView):
    model = Morceau

    def get_success_url(self):
        return reverse('musiques:morceau-list')

musiques/templates/musiques/artiste.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Artiste : {{object.nom}}</h2>
<table class="table-striped">
    <tr class="row">
        <td class="col-md-6"><h3>Track list</h3></td>
        <td class="col-md-6"></td>
    </tr>
    {% for m in object.morceau_set.all %}
    <tr class="row">
        <td class="col-md-6"></td>
        <td class="col-md-6">{{m.titre}}</td>
    </tr>    
    {% endfor %}
</table>
<a href="{% url 'musiques:artiste-list'%}">
    <span class="glyphicon glyphicon-chevron-left">Retour</span>
</a>
{% endblock %}

musiques/templates/musiques/artiste_confirm_delete.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Delete Morceau</h2>
<form action="" method="post">{% csrf_token %}
    <p>Voulez-vous supprimer le morceau: "{{ artiste.nom }}"?</p>
    <input type="submit" value="Delete" />
</form>
<a href="{% url 'musiques:artiste-list'%}">
    <span class="glyphicon glyphicon-chevron-left">Retour</span>
</a>
{% endblock %}

musiques/templates/musiques/artiste_form.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Add artiste</h2>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
<a href="{% url 'musiques:artiste-list'%}">
    <span class="glyphicon glyphicon-chevron-left">Retour</span>
</a>
{% endblock %}

musiques/templates/musiques/artiste_list.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Artistes</h2>
<table class="table-striped">
    <tr class="row">
        <td class="col-md-3"><h3>ID</h3></td>
        <td class="col-md-3"><h3>Nom Artiste</h3></td>
        <td class="col-md-3"></td>
        <td class="col-md-3"></td>
    </tr>
{% for o in object_list %}
    <tr class="row">
        <td class="col-md-3">{{o.id}}</td>
        <td class="col-md-3"><a href="{% url 'musiques:artiste-detail' pk=o.id %}">{{o.nom}}</a></td>
        <td class="col-md-3">
            <a href="{% url 'musiques:artiste-del' pk=o.id %}">
                <span class="glyphicon glyphicon-remove"> Delete</span>
            </a>
        </td>
        <td class="col-md-3">
            <a href="{% url 'musiques:artiste-update' pk=o.id %}">
                <span class="glyphicon glyphicon-refresh"> Update</span>
            </a>
        </td>
    </tr>
{% empty %}
    <tr class="row">
        <td class="col-md-3"></td>
        <td class="col-md-3">Aucun artiste</td>
        <td class="col-md-3"></td>
        <td class="col-md-3"></td>
    </tr>
{% endfor %}
    <tr class="row">
        <td class="col-md-3"></td>
        <td class="col-md-3"></td>
        <td class="col-md-3"></td>
        <td class="col-md-3">
        <a href="{% url 'musiques:artiste-add' %}">
        <span class="glyphicon glyphicon-plus"> Add</span> 
        </a>
        </td>
    </tr>
</table>
{% endblock %}

musiques/templates/musiques/artiste_update.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Update artiste</h2>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href="{% url 'musiques:artiste-list'%}">
    <span class="glyphicon glyphicon-chevron-left">Retour</span>
</a>
{% endblock %}

musiques/templates/musiques/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/static/css/main.css">    
    <title>Shazam !</title>
</head>
<body class="container">
    <header class="row">
        <h1>Mon site de gestion de musique</h1>
        <ul class="nav col-md-4">
            <li class="col-md-5">
                <a href="{% url 'musiques:home' %}">Home</a>
            </li>
            <li role="presentation" class="dropdown col-md-5">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Action 
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'musiques:artiste-list' %}">List Artiste</a></li>
                    <li><a href="{% url 'musiques:morceau-list' %}">List Morceau</a></li>
                </ul>
            </li>
        </ul>
    </header>
    
    <main>
            {% block contenu %}{% endblock %}
    </main>

    <footer>
        <section>
            <p>Page concu et réaliser par Thibault MATHYS et Lucas CHARPENTIER.</p>
            <p>Tout droit réservé Thibault MATHYS, Lucas CHARPENTIER.</p>
        </section>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

musiques/templates/musiques/home.html
{% extends "musiques/base.html" %}
{% block contenu %}
<div class="row">
    <section class="col-md-6">
        <h3>Présentation</h3>
        <p>Ce site présente un ensemble d'Artiste et de Morceau.
            La barre de navigation vous permettra de visionenr, ajouter, modifier et supprimer
            des artiste et des morceau selon les artiste.
            Le site est réalisé avec le framework Django et l'extension bootstrap.
    
        </p>
    </section>
</div>
{% endblock %}

musiques/templates/musiques/morceau.html
{% extends "musiques/base.html" %}
{% block contenu %}
<section>
    <h2>Detail Morceau : {{ object.titre }}</h2>
    <p>Artiste : {{ object.artiste.nom }}</p>
</section>
<div class="row">
    <a class="col-md-3 "href="{% url 'musiques:morceau-list'%}">
        <span class="glyphicon glyphicon-chevron-left">Retour</span>
    </a>
</div>

{% endblock %}

musiques/templates/musiques/morceau_confirm_delete.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Delete Morceau</h2>
<form action="" method="post">{% csrf_token %}
    <p>Voulez-vous supprimer le morceau: "{{ morceau.titre }}"?</p>
    <input type="submit" value="Delete" />
</form>
<div class="row">
    <a class="col-md-3 "href="{% url 'musiques:morceau-list'%}">
        <span class="glyphicon glyphicon-chevron-left">Retour</span>
    </a>
</div>
{% endblock %}

musiques/templates/musiques/morceau_form.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Add Morceau</h2>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
<div class="row">
    <a class="col-md-3 "href="{% url 'musiques:morceau-list'%}">
        <span class="glyphicon glyphicon-chevron-left">Retour</span>
    </a>
</div>
{% endblock %}

musiques/templates/musiques/morceau_list.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Morceaux</h2>
<table class="table-striped">
    <tr class="row">
        <td class="col-md-3"><h3>Artiste</h3></td>
        <td class="col-md-2"><h3>ID</h3></td>
        <td class="col-md-3"><h3>Titre</h3></td>
        <td class="col-md-2"></td>
        <td class="col-md-2"></td>
    </tr>
{% for morceau in object_list %}
    <tr class="row">
        <td class="col-md-3">{{ morceau.artiste }}</td>
        <td class="col-md-2">{{ morceau.id }}</td>
        <td class="col-md-3"><a href="{% url 'musiques:morceau-detail' pk=morceau.id %}">{{ morceau.titre }}</a></td>
        <td class="col-md-2">
            <a href="{% url 'musiques:morceau-del' pk=morceau.id %}">
                <span class="glyphicon glyphicon-remove"> Delete</span>
            </a>
        </td>
        <td class="col-md-2">
            <a href="{% url 'musiques:morceau-update' pk=morceau.id %}" >
                <span class="glyphicon glyphicon-refresh"> Update</span>
            </a>
        </td>
    </tr>
{% empty %}
    <tr class="row">
        <td class="col-md-3"></td>
        <td class="col-md-2">Pas de morceaux.</td>
        <td class="col-md-3"></td>
        <td class="col-md-2"></td>
        <td class="col-md-2"></td>
    </tr>
{% endfor %}
    <tr class="row">
        <td class="col-md-3"></td>
        <td class="col-md-2"></td>
        <td class="col-md-3"></td>
        <td class="col-md-2"></td>
        <td class="col-md-2">
        <a href="{% url 'musiques:morceau-add' %}">
            <span class="glyphicon glyphicon-plus"> Add</span>
        </a>
        </td>
    </tr>
</table>
{% endblock %}

musiques/templates/musiques/morceau_update.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Update Morceau</h2>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<div class="row">
    <a class="col-md-3 "href="{% url 'musiques:morceau-list'%}">
        <span class="glyphicon glyphicon-chevron-left">Retour</span>
    </a>
</div>
{% endblock %}